### ISSUE TITLE
Query is not working when changing regional settings to different time format

### ISSUE THREAD

**Issue by napsteroid** [fgimian/pyremedy#4]
Hello, 
I have issues with query function after changing regional settings to different time format. It works perfectly when format is set to MM/dd/yyyy, but when i change date format to dd-MMM-yy it doesn't work and pyremedy raising error message Message 1590: Format of time value is not recognized, even if i format qualification string to MM/dd/yyyy. 
Please any suggestions why this is happening, and what might be a solution ?

Thanks for any kind of help,

Michael

**Comment by fgimian** [comment]
I'm not sure where you're changing the time format but I don't control any aspect of entering time in PyRemedy.  The error you're receiving is coming from Remedy itself.  I suggest trying the query in the BMC Remedy UI first.

**Comment by napsteroid** [comment]
Hi Gimian,

I´ve already found out why this issue was occurring, basically i adjusted
pyRemedy for working on Win machine, and it was issue with windows local
time/zone settings. Anyway you did a really great job with pyRemedy, it
helped us a lot with automation of the Remedy. Really appreciate that.

Have a nice day and happy new year ,


Michael

2016-12-30 16:44 GMT+01:00 Fotis Gimian <notifications@github.com>:

**Comment by fgimian** [comment]
Thanks Michael 😄
